import './indydcp-dis'
import './indydcp-do'
import './indydcp-ais'
import './indydcp-ao'
import './indydcp-move'
import './indydcp-home'
import './indydcp-zero'
import './indydcp-run'

import './indydcp-control'
import './indydcp-di-wait'
import './indydcp-reset'
import './indydcp-set-speed'
import './indydcp-status'
import './indydcp-task-move'